name: 'Subnet Calculator'
description: 'To calculate subnets for allocation'
inputs:
  subnet:
    description: 'Enter subnet with mask'
    required: false
    default: 'true'
outputs:
  used-cache:
    description: 'Whether the cache was used.'
    value: ${{ steps.result.outputs.res }}
runs:
  using: 'composite'
  steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: execute py script # run the run.py to get the latest data
        id: result
        run: |
          python fin.py 10.0.0.0/21 > sub-result.txt
          res=$(echo 'head -n1 ./sub-result.txt) 
          echo "res=$res" >> $GITHUB_OUTPUT
        shell: bash
