name: 'Subnet Calculator'
description: 'To calculate subnets for allocation'
inputs:
  subnet:
    description: 'Enter subnet with mask'
    required: false
    default: 'true'
outputs:
  networkAddress:
    description: 'networkAddress'
    value: ${{ steps.result1.outputs.networkAddress }}
  broadcastAddress:
    description: 'broadcastAddress'
    value: ${{ steps.result1.outputs.broadcastAddress }}
runs:
  using: 'composite'
  steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: execute py script # run the run.py to get the latest data
        id: result
        run: |
          python fin.py 10.0.0.0/21 > sub-result.txt
          cat sub-result.txt
        shell: bash
      - name: networkAddress
        id: result1
        run: |
          networkAddress=$(echo `head -n1 ./sub-result.txt`) 
          echo "action out $networkAddress" 
          echo "networkAddress=$networkAddress" >> $GITHUB_OUTPUT
        shell: bash
      - name: networkAddress
        id: result2
        run: |
          broadcastAddress=$(echo `head -n2 ./sub-result.txt`) 
          echo "action out $broadcastAddress" 
          echo "broadcastAddress=$broadcastAddress" >> $GITHUB_OUTPUT
        shell: bash
