name: demo-3
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: | 
          CURRENT_USERS=$(who)
          echo "OSNAME = $CURRENT_USERS" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo ${{ steps.step1.outputs.OSNAME}}
