name: demo-3
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: get osname
        id: osname
        run: |
          OUTPUT=$(uname -r)
          echo "${OUTPUT}"
