name: demo-3
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: | 
          OS_NAME = $(uname -r)
          echo "OSNAME = $OS_NAME" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo ${{ steps.step1.outputs.OSNAME}}
