name: Cache
on: workflow_dispatch
jobs:
  deploy-dev:
    environment: dev  
    runs-on: ubuntu-latest
    steps:
      - name: Install terraform app
        run: |
         echo $tfVersion
         wget  https://releases.hashicorp.com/terraform/${{vars.TFVERSION}}/terraform_${{vars.TFVERSION}}_linux_amd64.zip
         sudo unzip -o terraform_${{vars.TFVERSION}}_linux_amd64.zip -d /usr/local/bin
         terraform -version   
  deploy-demo:
    needs: deploy-dev
    environment: dev  
    runs-on: ubuntu-latest
    steps:
      - name: Install terraform
        run: |
         echo $tfVersion
         wget  https://releases.hashicorp.com/terraform/$${{vars.TFVERSION}}/terraform_${{vars.TFVERSION}}_linux_amd64.zip
         sudo unzip -o terraform_${{vars.TFVERSION}}_linux_amd64.zip -d /usr/local/bin
         terraform -version


          
