name: pyscript-custom
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: setup python
        id: subnet
        uses: ./.github/actions/
        with:
          subnet: 10.0.0.0/21
      - name: Output information
        run: |
          echo "networkAddress fetched ${{ steps.subnet.outputs.networkAddress  }}"
          echo "broadcastAddress fetched ${{ steps.subnet.outputs.broadcastAddress  }}"
          echo "broadcastAddress fetched ${{ steps.subnet.outputs.subnetMask   }}"
          echo "broadcastAddress fetched ${{ steps.subnet.outputs.wildcardMask   }}"
          echo "broadcastAddress fetched ${{ steps.subnet.outputs.firstIP   }}"
          echo "broadcastAddress fetched ${{ steps.subnet.outputs.LastIP   }}"
