name: gh-w01
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    outputs:
        output1: ${{ steps.os_info.outputs.os_name }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Run a script
        run: sudo bash ${GITHUB_WORKSPACE}/sys_info_1.sh
      - name: publish output
        id: os_info
        run: echo "OS_NAME = uname -r" >> $GITHUB_OUTPUT
      - name: Retrieve output
        run: echo " os_name is ${{ steps.os_info.outputs.OS_NAME }}"
      - name: Set color
        id: random-color-generator
        run: echo "SELECTED_COLOR=green" >> $GITHUB_OUTPUT
      - name: Get color
        run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sys-info
          path: sysInfo
      

