name: gh-w01
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Run a script
        run: sudo bash ${GITHUB_WORKSPACE}/sys_info_1.sh
      - name: publish output
        id: os_info
        run: |
          os_name = uname -r 
          osname >> $GITHUB_OUTPUT
      - name: Example output call between steps
        run: |
          echo "Output [${{steps.os_info.outputs.os_name}}]"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sys-info
          path: sysInfo
      

