name: gh-w01
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: |
          echo "My First Workflow"
          sudo apt update
          sudo apt install nginx
          sudo ufw app list
          sudo ufw allow 'Nginx HTTP'
          systemctl status nginx
          curl -4 icanhazip.com
      - name: Print Bye
        run: echo "GoodBye"
        
