name: gh-w01
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: |
          echo "My First Workflow"
          sudo apt install telnet
          telnet localhost 80
          sudo apt update
          sudo apt install nginx
          curl http://localhost:80
      - name: Print Bye
        run: echo "GoodBye"
        
