name: container
on: workflow_dispatch

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.6
    steps:
     - name: Log the parent container node version
       run: |
         terraform -version
     - name: Get code
       uses: actions/checkout@v3
     - name: initiaize
       run: |
         cd ./terraform
         terraform init
         terraform fmt
         terraform validate
         cat main.tf
