name: container
on: workflow_dispatch

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:latest
    steps:
     - name: Log the parent container node version
       run: |
         terraform -version
