name: Expressions
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: first-step
        run: |
          echo “Display A Figlet"
          sudo apt-get install figlet
          figlet "Linux Rocks!"
      - name: End-Workflow
        run: echo “Execution is completed"

       
