name: Expressions
on: workflow_dispatch
jobs:
  expressions-job:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: echo "${{ toJson(github) }}"
      - name: Github Repo
        run: echo "${{ toJson(github.repository) }}"
      - name: Dump runner context
        run: echo "${{ toJson(runner) }}"
      - name: Dump strategy context
        run: echo "${{ toJson(strategy) }}"
