name: if-condition
on: workflow_dispatch
jobs:
  condtional-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        run: |
          echo -e "This Linux Distro. Used On this computer `head -n1 /etc/issue`
