name: if-condition
on: workflow_dispatch
jobs:
  condtional-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get OS info
        id: osinfo
        run: |
          result=$(echo `head -n1 /etc/issue`)
          echo $result
          echo "result=$result" >> $GITHUB_OUTPUT
      - name: Validate OS
        run: |
          echo "${{ steps.osinfo.outputs.result}}"
