name: if-condition
on: workflow_dispatch
jobs:
  condtional-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get OS info
        id: osinfo
        run: |
          result=$(echo `head -n1 /etc/issue`)
          echo "result=$result" >> $GITHUB_OUTPUT
      - name: git repo
        run: |
          echo ${{ github.repository}}         
      - name: Validate OS
        run: |
          if ${{ steps.osinfo.conclusion == 'success' }}
          echo "${{ steps.osinfo.outputs.result}}"
          
