name: if-condition
on: workflow_dispatch
jobs:
  condtional-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        run: |
          echo "result=$result `head -n1 /etc/issue`" >> $GITHUB_OUTPUT
