name: if-condition
on: workflow_dispatch
jobs:
  condtional-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get OS info
        id: osinfo
        run: |
          echo "result=$result `head -n1 /etc/issue`" >> $GITHUB_OUTPUT
      - name: Validate OS
        run: |
          echo "${{ steps.osinfo.outputs.resul}}"
