name: Explore vars and secrets
on: workflow_dispatch
env:
  AWS_ACCESS_KEY_ID: ${{vars.AWS_ACCESS_KEY}}
jobs:
  Configure:
    environment: demo  
    runs-on: ubuntu-latest
    steps:
      - name: check tfversion
        run: echo ${{vars.TFVERSION}}
      - name: Configure AWS Profile
        run: |
          export AWS_SECRET_ACCESS_KEY=${{vars.AWS_SECRET_KEY}}
          export AWS_REGION=us-east-1
          env
      - name: Validate input
        run: |
          env
          
