name: Explore vars and secrets
on: workflow_dispatch
jobs:
  Configure:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Profile
        run: |
          sudo export AWS_ACCESS_KEY_ID=${{vars.AWS_ACCESS_KEY}}
          sudo export AWS_SECRET_ACCESS_KEY=${{vars.AWS_SECRET_KEY}}
          sudo export AWS_REGION=us-east-1
      - name: Validate input
        run: env
          
